// services/tables/dungeon_table_service.dart

import '../../models/dto/dungeon_table_dto.dart';
import '../../utils/dice_roller.dart';

class DungeonTableService {
  static const List<DungeonTableDto> _tableData = [
    // Coluna 1 - Tipo
    DungeonTableDto(
      type: 'Construção Perdida',
      builderOrInhabitant: 'Desconhecido',
      status: 'Amaldiçoados',
      objective: 'Defender',
      location: 'Deserto Escaldante',
      entry: 'Atrás de uma Cachoeira',
      roomsCountFormula: 'Grande – 3d6+4',
      occupant1: 'Trolls',
      occupant2: 'Kobolds',
      leader: 'Hobgoblin',
      rumorSubject: 'Um/uma [coluna 11] decapitada/o',
      rumorAction: 'foi visto próximo a',
      rumorContext: 'festival religioso do outono',
    ),
    DungeonTableDto(
      type: 'Construção Perdida',
      builderOrInhabitant: 'Desconhecido',
      status: 'Amaldiçoados',
      objective: 'Defender',
      location: 'Deserto Escaldante',
      entry: 'Atrás de uma Cachoeira',
      roomsCountFormula: 'Grande – 3d6+4',
      occupant1: 'Trolls',
      occupant2: 'Kobolds',
      leader: 'Hobgoblin',
      rumorSubject: 'Um/uma [coluna 11] decapitada/o',
      rumorAction: 'foi visto próximo a',
      rumorContext: 'festival religioso do outono',
    ),
    DungeonTableDto(
      type: 'Labirinto Artificial',
      builderOrInhabitant: 'Cultistas',
      status: 'Extintos',
      objective: 'Esconder',
      location: 'Sob uma Cidade',
      entry: 'Túnel Secreto',
      roomsCountFormula: 'Média – 2d6+4',
      occupant1: 'Orcs',
      occupant2: 'Limo Cinzento',
      leader: 'Cubo Gelatinoso',
      rumorSubject: 'Um camponês bêbado',
      rumorAction: 'foi capturado na/no',
      rumorContext: 'vila no ano passado durante o eclipse',
    ),
    DungeonTableDto(
      type: 'Labirinto Artificial',
      builderOrInhabitant: 'Cultistas',
      status: 'Extintos',
      objective: 'Esconder',
      location: 'Sob uma Cidade',
      entry: 'Túnel Secreto',
      roomsCountFormula: 'Média – 2d6+4',
      occupant1: 'Orcs',
      occupant2: 'Limo Cinzento',
      leader: 'Cubo Gelatinoso',
      rumorSubject: 'Um camponês bêbado',
      rumorAction: 'foi capturado na/no',
      rumorContext: 'vila no ano passado durante o eclipse',
    ),
    DungeonTableDto(
      type: 'Cavernas Naturais',
      builderOrInhabitant: 'Civilização Ancestral',
      status: 'Ancestrais',
      objective: 'Proteger',
      location: 'Montanha Gelada',
      entry: 'Pequena Gruta',
      roomsCountFormula: 'Pequena – 1d6+4',
      occupant1: 'Esqueletos',
      occupant2: 'Zumbis',
      leader: 'Cultista',
      rumorSubject: 'Um/uma [coluna 10]',
      rumorAction: 'deixou rastros na/no',
      rumorContext: 'fazenda quando uma ovelha sumiu',
    ),
    DungeonTableDto(
      type: 'Cavernas Naturais',
      builderOrInhabitant: 'Civilização Ancestral',
      status: 'Ancestrais',
      objective: 'Proteger',
      location: 'Montanha Gelada',
      entry: 'Pequena Gruta',
      roomsCountFormula: 'Pequena – 1d6+4',
      occupant1: 'Esqueletos',
      occupant2: 'Zumbis',
      leader: 'Cultista',
      rumorSubject: 'Um/uma [coluna 10]',
      rumorAction: 'deixou rastros na/no',
      rumorContext: 'fazenda quando uma ovelha sumiu',
    ),
    DungeonTableDto(
      type: 'Covil Desabitado',
      builderOrInhabitant: 'Anões',
      status: 'Desaparecidos',
      objective: 'Guardar',
      location: 'Floresta Selvagem',
      entry: 'Fissura numa Rocha',
      roomsCountFormula: 'Pequena – 1d6+6',
      occupant1: 'Goblins',
      occupant2: 'Ratos Gigantes',
      leader: 'Sombra',
      rumorSubject: 'Um estrangeiro muito rico',
      rumorAction: 'procurou o sacerdote na/no',
      rumorContext: 'aldeia vizinha próxima',
    ),
    DungeonTableDto(
      type: 'Covil Desabitado',
      builderOrInhabitant: 'Anões',
      status: 'Desaparecidos',
      objective: 'Guardar',
      location: 'Floresta Selvagem',
      entry: 'Fissura numa Rocha',
      roomsCountFormula: 'Pequena – 1d6+6',
      occupant1: 'Goblins',
      occupant2: 'Ratos Gigantes',
      leader: 'Sombra',
      rumorSubject: 'Um estrangeiro muito rico',
      rumorAction: 'procurou o sacerdote na/no',
      rumorContext: 'aldeia vizinha próxima',
    ),
    DungeonTableDto(
      type: 'Fortaleza Abandonada',
      builderOrInhabitant: 'Magos',
      status: 'Perdidos',
      objective: 'Vigiar',
      location: 'Pântano Fétido',
      entry: 'Covil de um Monstro',
      roomsCountFormula: 'Média – 2d6+6',
      occupant1: 'Bugbears',
      occupant2: 'Fungos Pigmeu',
      leader: 'Necromante',
      rumorSubject: 'Um místico cego',
      rumorAction: 'foi morto por um lobisomem na/no',
      rumorContext: 'caravana de comércio da primavera',
    ),
    DungeonTableDto(
      type: 'Fortaleza Abandonada',
      builderOrInhabitant: 'Magos',
      status: 'Perdidos',
      objective: 'Vigiar',
      location: 'Pântano Fétido',
      entry: 'Covil de um Monstro',
      roomsCountFormula: 'Média – 2d6+6',
      occupant1: 'Bugbears',
      occupant2: 'Fungos Pigmeu',
      leader: 'Necromante',
      rumorSubject: 'Um místico cego',
      rumorAction: 'foi morto por um lobisomem na/no',
      rumorContext: 'caravana de comércio da primavera',
    ),
    DungeonTableDto(
      type: 'Mina Desativada',
      builderOrInhabitant: 'Gigantes',
      status: 'em outro local',
      objective: 'Isolar',
      location: 'Ilha Isolada',
      entry: 'Boca de um Vulcão',
      roomsCountFormula: 'Grande – 3d6+6',
      occupant1: 'Ogros',
      occupant2: 'Homens Lagartos',
      leader: 'Dragão',
      rumorSubject: '[coluna 12]',
      rumorAction: 'amaldiçoou a/o',
      rumorContext: 'nevasca do inverno há 3 anos',
    ),
    DungeonTableDto(
      type: 'Mina Desativada',
      builderOrInhabitant: 'Gigantes',
      status: 'em outro local',
      objective: 'Isolar',
      location: 'Ilha Isolada',
      entry: 'Boca de um Vulcão',
      roomsCountFormula: 'Grande – 3d6+6',
      occupant1: 'Ogros',
      occupant2: 'Homens Lagartos',
      leader: 'Dragão',
      rumorSubject: '[coluna 12]',
      rumorAction: 'amaldiçoou a/o',
      rumorContext: 'nevasca do inverno há 3 anos',
    ),
  ];

  static DungeonTableDto roll() {
    final roll = DiceRoller.roll(2, 6);
    return _tableData[roll - 2];
  }

  static String resolveColumnReference(String text, DungeonTableDto data) {
    return text
        .replaceAll('[coluna 10]', data.occupant1)
        .replaceAll('[coluna 11]', data.occupant2)
        .replaceAll('[coluna 12]', data.leader);
  }
}
